version: 0.1

default:
  global:
    parameters:
      stack_name: handover-backend
      s3_prefix: handover-backend
      resolve_s3: true
      resolve_image_repositories: true
  build:
    parameters:
      cached: true
      parallel: true
  deploy:
    parameters:
      disable_rollback: true
      confirm_changeset: false
      fail_on_empty_changeset: false
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
  validate:
    parameters:
      lint: true
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: EAGER
  local_start_lambda:
    parameters:
      warm_containers: EAGER